spring.application.name=Boardroom-Booking

# PostgreSQL Example
spring.datasource.url=jdbc:postgresql://localhost:5432/boardroom
spring.datasource.username=postgres
spring.datasource.password="Chichi@dolls2024"

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Timezone
spring.jpa.properties.hibernate.jdbc.time_zone=Africa/Nairobi

# Reduce overall logging noise
logging.level.root=warn
#logging.level.org.springframework.boot=info



